language: go

git:
  depth: 1

env:
  - GO111MODULE=on

go:
  - 1.12.x

cache:
  directories:
    - /home/travis/gopath/pkg/mod
    - /home/travis/.cache/go-build

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      name: Build binary
      script:
        - ./build.sh

    - stage: test
      name: Check gofmt
      script:
        - ./scripts/check-gofmt.sh

    - stage: test
      name: Integration Tests
      script:
        - docker run -dt --name redis_1 -p 6379:6379 redis:4
        - docker run -dt --name redis_2 -p 6389:6379 redis:4
        - export LMSTFY_TEST_CONFIG=`pwd`/scripts/test-conf.toml
        - ./scripts/run-test.sh
